### ISSUE TITLE
ninix-aya/ninix-kagari variant of ukagaka-simultaneous-interpreter ghost mod?

### ISSUE THREAD

**Issue by ribbybbir** [Tatakinov/ninix-kagari#2]
Tatakinovさん、こんにちは、

2週間前のアップグレードで、virustotal.comのマルウェアスキャンサービスがクリアされたようですね。
https://www.virustotal.com/gui/file/01db5aaa3b21bfe0ce742dc7e32b5d41574742446da2e7cf2f5c2c78f3ed4cad/relations
mitreの手口/シグネチャにクリアランスが必要だと指摘する人もいるかもしれませんが、これらのレポートは、悪意のあるマルウェア/アクティビティというよりは、潜在的な/疑わしいアクティビティに関するものです。いずれにせよ、ある程度のリスクは常にあります。

Ghost、balloon、その他のninix亜種のモジュール機能は、機能だけでなくモジュールの量も制限されていた。ニニックスかがりのテストランが必要かもしれない。

+アイリ＆トウマ
https://web.archive.org/web/20040602234054/http://yth.cool.ne.jp/nanika/
https://web.archive.org/web/20040602234054/http://yth.cool.ne.jp/nanika/sample_airi.jpg
https://web.archive.org/web/20040602234054/http://yth.cool.ne.jp/nanika/airi-3.02.nar

+アイラ
https://web.archive.org/web/20020810200615/http://www.ipc-tokai.or.jp/~tenchi/nanika/ai.htm
プレビュー画像
https://web.archive.org/web/20020810200615/http://www.ipc-tokai.or.jp/~tenchi/nanika/air_plot15.na

+黒ニー英語版
https://www.reddit.com/r/ukagakaghost/comments/1ba99or/comment/ku2eew4/?utm_source=reddit&utm_medium=web2x&context=3
https://docs.google.com/document/d/10fRA2bv8baV9W8mOdstXUcnLl1xLB5PRKC5_F9PSTpM/edit
https://drive.google.com/file/d/1MDuhOUET8OvPPWjlN5FvSH95NO5fLwPb/view?usp=share_link

misaka.dllを使用した、みなし安全モジュールです。

+無彩色
https://web.archive.org/web/20240908001730/https://tokiwa.illust.jp/?page_id=2
https://web.archive.org/web/20240908001730im_/https://tokiwa.illust.jp/wp-content/uploads/2023/09/shiori_S.png
https://web.archive.org/web/20240908001730/https://tokiwa.illust.jp/wp-content/uploads/2021/05/Achromatic_Color.zip

+古傷のエルフィナ
https://web.archive.org/web/20220625192030/https://nanachi.sakura.ne.jp/narnaloader/ghost.php?ghost=old_sign
https://web.archive.org/web/20220612110000im_/https://nanachi.sakura.ne.jp/narnaloader/data/old_sign/nnl/preview_generated.png
https://web.archive.org/web/20240909132303/https://nanachi.sakura.ne.jp/narnaloader/nar/old_sign.nar
-体を焼くように」シェル/スキン
https://web.archive.org/web/20220615133147/https://snowfragment.sakura.ne.jp/scorchingsummer.html
https://web.archive.org/web/20220615133147im_/https://snowfragment.sakura.ne.jp/pict/scorchingsummerss.png
https://web.archive.org/web/20220615133147/https://snowfragment.sakura.ne.jp/nar/scorchingsummer.nar

これらの安全とみなされたモジュールはsatori.dllを使用し、virustotal.comのマルウェアスキャンサービスによるとマルウェアはありません。なお、ninix-kagari baseware、Achromatic Color ghost module、古傷elphina ghost moduleの両方をテストします（「体を焼くように 」シェルモジュールも一緒に）。万が一マルウェアがあったとしても、少なくとも信用情報機関への詐欺警告申請は被害を減らすことができるだろう。

SSP準拠のモジュールに関しては、通常、SSPベースウェア・プログラムやsatori.dll/saori.dllによって汚染されている。例外はシェルモジュールである。将来、ninix/ninix-aya/ninix-kagariがSSPに取って代わることは明らかである。SSPモジュールはninix-kagariフォーマットを必要とします。私は、ukagaka-simultaneous-interpreter ghost module の SSP バリアントを ninix-kagari 形式に書き換えることを要望します。このモジュールがあれば、多くのユーザーや開発者が言語の壁なしにこのプログラムや他のモジュールにアクセスすることができます。もちろん、ヨメ狐のような通常の幽霊モジュールも、花嫁狐や狐の嫁入りシェルモジュールとともに、ninix-kagariへの書き換えを歓迎する。チャラリナ・モジュールも忘れてはならない。

---

Hello Tatakinov,

It seems that the malware scanning service on virustotal.com was cleared after the upgrade two weeks ago.
https://www.virustotal.com/gui/file/01db5aaa3b21bfe0ce742dc7e32b5d41574742446da2e7cf2f5c2c78f3ed4cad/relations
Some might point out that the mitre's M.O.s/signatures need clearance, but these reports are about potential/suspicious activity rather than malicious malware/activity. In any case, there is always some degree of risk.

The modular functionality of Ghost, balloon, and other ninix variants was limited not only in functionality but also in the amount of modules. A test run of Ninix Kari may be needed.

+airi & toma
https://web.archive.org/web/20040602234054/http://yth.cool.ne.jp/nanika/
https://web.archive.org/web/20040602234054/http://yth.cool.ne.jp/nanika/sample_airi.jpg
https://web.archive.org/web/20040602234054/http://yth.cool.ne.jp/nanika/airi-3.02.nar

+Ayla
https://web.archive.org/web/20020810200615/http://www.ipc-tokai.or.jp/~tenchi/nanika/ai.htm
Preview image
https://web.archive.org/web/20020810200615/http://www.ipc-tokai.or.jp/~tenchi/nanika/air_plot15.na

+Black Knee English version
https://www.reddit.com/r/ukagakaghost/comments/1ba99or/comment/ku2eew4/?utm_source=reddit&utm_medium=web2x&context=3
https://docs.google.com/document/d/10fRA2bv8baV9W8mOdstXUcnLl1xLB5PRKC5_F9PSTpM/edit
https://drive.google.com/file/d/1MDuhOUET8OvPPWjlN5FvSH95NO5fLwPb/view?usp=share_link

Deemed safe module using misaka.dll.

+non-color
https://web.archive.org/web/20240908001730/https://tokiwa.illust.jp/?page_id=2
https://web.archive.org/web/20240908001730im_/https://tokiwa.illust.jp/wp-content/uploads/2023/09/shiori_S.png
https://web.archive.org/web/20240908001730/https://tokiwa.illust.jp/wp-content/uploads/2021/05/Achromatic_Color.zip

+Elfina of Old Wounds
https://web.archive.org/web/20220625192030/https://nanachi.sakura.ne.jp/narnaloader/ghost.php?ghost=old_sign
https://web.archive.org/web/20220612110000im_/https://nanachi.sakura.ne.jp/narnaloader/data/old_sign/nnl/preview_generated.png
https://web.archive.org/web/20240909132303/https://nanachi.sakura.ne.jp/narnaloader/nar/old_sign.nar
-“As if burning the body” shell/skin
https://web.archive.org/web/20220615133147/https://snowfragment.sakura.ne.jp/scorchingsummer.html
https://web.archive.org/web/20220615133147im_/https://snowfragment.sakura.ne.jp/pict/scorchingsummerss.png
https://web.archive.org/web/20220615133147/https://snowfragment.sakura.ne.jp/nar/scorchingsummer.nar

These deemed safe modules use satori.dll and have no malware according to the virustotal.com malware scanning service. Note that we test both ninix-kagari baseware, Achromatic Color ghost module and old wounded elphina ghost module (along with the “Burn the body” shell module). In the unlikely event that there is malware, at least a fraud alert application to the credit bureaus will reduce the damage.

As for SSP-compliant modules, they are usually contaminated by SSP baseware programs and satori.dll/saori.dll. The exception is the shell module. It is clear that ninix/ninix-aya/ninix-kagari will replace SSP in the future; the SSP module requires the ninix-kagari format. I request that the SSP variant of the ukagaka-simultaneous-interpreter ghost module be rewritten in ninix-kagari format. With this module, many users and developers can access this program and other modules without language barriers. Of course, the usual ghost modules like yome-fox are also welcome to be rewritten to ninix-kagari, along with the bride-fox and fox-bride shell modules. Not forgetting the charalina module.

**Comment by Tatakinov** [comment]
I made it.
https://github.com/Tatakinov/my_own_translator
Update yaya to the latest version, make ninix-saori and copy it to the specified location and it will work.
https://github.com/Tatakinov/ninix-saori
