### ISSUE TITLE
[Request] .deb installation file?

### ISSUE THREAD

**Issue by ribbybbir** [Tatakinov/ninix-kagari#4]
なぜインストールにruby言語が必要なのか理解できないが、これらはこのninix-kagari variantの依存ファイルである。.debインストールファイルの方がユーザーにとって簡単な方法だと思います。Go言語がGNU/Linuxライセンス標準に準拠していないのは、Googleの評判のせいだというのが私の個人的な意見だ。

とにかく、依存関係を手動でインストールすることにしよう。

v
+0 を再開する：
#ninix

+エラー 1：
mkdir -p /opt/ninix-kagari/lib
cp -r lib/* /opt/ninix-kagari/lib
mkdir -p /usr/local/share/locale/ja/LC_MESSAGES
cd po/ja ; msgfmt po/ja/ninix-kagari.po -o /usr/local/share/locale/ja/LC_MESSAGES/ninix-kagari.mo
/bin/sh: 1: msgfmt: 見つかりません。
make： *** エラー 127

+解決方法 1：
https://www.gnu.org/software/gettext/manual/gettext.html
https://unix.stackexchange.com/questions/516669/msgfmt-not-found-though-msgfmt-is-installed-via-package-manager

#apt install gettext

+再開 1：
#make install
#PATH=/opt/ninix-kagari/bin:$PATH

+エラー 2：
トレースバック (最新の呼び出し)：
	1: from /opt/ninix-kagari/lib/ninix_main.rb:22:in `<main>'.
/opt/ninix-kagari/lib/ninix_main.rb:22:in `require_relative': cannot load such file -- /opt/ninix-kagari/lib/ninix/pix (LoadError).

+解決策 2：
https://github.com/Tatakinov/ninix-kagari#library
https://github.com/Tatakinov/kawari
https://github.com/Tatakinov/yaya-shiori

+エラー 3：
-河合ライブラリーの失敗
https://www.virustotal.com/gui/file/0811e29c86aa4d4dd4daba9f9db42c6036dd872c796c6f32ae82b6115601124f/detection
-やしおりライブラリ障害
https://www.virustotal.com/gui/file/bdb38308804202b1ab926e79374be4b1a0e9e5f2a2f128942b4d21441342ec16/relations

+解決策3：
ninix亜種の作者が関与していない。問題は悪意のあるライブラリにある。

#ベータプログラムのバージョンとライブラリの削除
#apt-get --purge remove gettext
#apt-get --purge remove ninix-aya
#apt 自動削除
#rm -r /opt/ninix-kagari

#安定版プログラム(およびライブラリ)のインストール
#apt-get install ninix-aya
#apt-get install kawari8 (推奨パッケージ)

---

I don't understand why the ruby language is needed for installation, but these are the dependency files of this ninix-kagari variant. I think the .deb install file is an easier way for users, and it is my personal opinion that the Go language is not compliant with the GNU/Linux licensing standard because of Google's reputation.

Anyway, I would install the dependencies manually.
v
+0 to resume:
#ninix

+Error 1:
mkdir -p /opt/ninix-kagari/lib
cp -r lib/* /opt/ninix-kagari/lib
mkdir -p /usr/local/share/locale/en/LC_MESSAGES
cd po/en ; msgfmt po/en/ninix-kagari.po -o /usr/local/share/locale/en/LC_MESSAGES/ninix-kagari.mo
/bin/sh: 1: msgfmt: not found.
make: *** error 127

+Solution 1:
https://www.gnu.org/software/gettext/manual/gettext.html
https://unix.stackexchange.com/questions/516669/msgfmt-not-found-though-msgfmt-is-installed-via-package-manager

#apt install gettext

+Resume 1:
#make install
#PATH=/opt/ninix-kagari/bin:$PATH

+Error 2:
Traceback (latest call):
	1: from /opt/ninix-kagari/lib/ninix_main.rb:22:in `<main>'.
/opt/ninix-kagari/lib/ninix_main.rb:22:in `require_relative': cannot load such file -- /opt/ninix-kagari/lib/ninix/pix (LoadError).

+Solution 2:
https://github.com/Tatakinov/ninix-kagari#library
https://github.com/Tatakinov/kawari
https://github.com/Tatakinov/yaya-shiori

+Error 3:
-Kawaii library failure
https://www.virustotal.com/gui/file/0811e29c86aa4d4dd4daba9f9db42c6036dd872c796c6f32ae82b6115601124f/detection
-Ya Bookmark Library Failure
https://www.virustotal.com/gui/file/bdb38308804202b1ab926e79374be4b1a0e9e5f2a2f128942b4d21441342ec16/relations

+Solution 3:
The author of the ninix variant is not involved. The problem lies in the malicious library.

#remove beta program version and library.
#apt-get --purge remove gettext
#apt-get --purge remove ninix-aya
#apt auto-remove.
#rm -r /opt/ninix-kagari

#install stable programs (and libraries)
#apt-get install ninix-aya
#apt-get install kawari8 (recommended package)

**Comment by Tatakinov** [comment]
I made it but never tested it.
https://github.com/Tatakinov/ninix-kagari/releases/tag/v1.7.0

**Comment by ribbybbir** [comment]
So far, everything looks good by virustotal.com malware scan results except for the relations tab details.

https://www.virustotal.com/gui/file/c52a01724813b1c99ee939dafd9ecdbfdd183449db12764dc7e8edf6323ec70d/relations

I know I am a bit pensive, but SSP and its derivative is a risky program!
